import { app, BrowserWindow, ipcMain, shell, protocol, net } from 'electron'
import path from 'path'
import fs from 'fs'
import { initDb } from './db'

// Must be called before app.whenReady()
protocol.registerSchemesAsPrivileged([
  { scheme: 'localfile', privileges: { secure: true, standard: false, supportFetchAPI: true, corsEnabled: true } }
])
import { startPreviewServer } from './preview-server'

const isDev = process.env.NODE_ENV === 'development'

function createWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  })

  if (isDev) {
    win.loadURL('http://localhost:5173')
    win.webContents.openDevTools()
  } else {
    win.loadFile(path.join(__dirname, '../renderer/index.html'))
  }
}

app.whenReady().then(async () => {
  // localfile:///abs/path → file:///abs/path, bypasses Electron CSP for local images
  protocol.handle('localfile', (request) =>
    net.fetch(request.url.replace('localfile://', 'file://'))
  )

  await initDb()
  startPreviewServer(3456)
  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

// IPC handlers registered in separate modules
import './ipc/posts'
import './ipc/publish'

ipcMain.handle('preview:open', (_e, postId: number) => {
  shell.openExternal(`http://localhost:3456/preview/${postId}`)
})

import { getModelsStatus, downloadModel, setActiveModel, extractWithAI } from './ai'

ipcMain.handle('models:status', () => getModelsStatus())

ipcMain.handle('models:download', async (event, modelId: string) => {
  await downloadModel(modelId, progress => {
    event.sender.send('models:download-progress', progress)
  })
})

ipcMain.handle('models:setActive', (_e, modelId: string) => setActiveModel(modelId))

ipcMain.handle('ai:extract', (_e, rawText: string) => extractWithAI(rawText))

import { loadSettings, saveSettings } from './settings'
ipcMain.handle('settings:load', () => loadSettings())
ipcMain.handle('settings:save', (_e, s: Record<string, string>) => saveSettings(s))

import { hasCookies, loginWithQR, probeCdp } from './publishers/xiaohongshu'
import { spawnSync, execSync } from 'child_process'
import os from 'os'

// ── LaunchAgent helpers (Chrome CDP background service) ──────────────────────

const AGENT_LABEL = 'com.xiaoheishu.chrome-debug'
const AGENT_SCRIPT = path.join(os.homedir(), 'Library', 'Scripts', 'xiaoheishu-chrome-debug.sh')
const AGENT_PLIST  = path.join(os.homedir(), 'Library', 'LaunchAgents', `${AGENT_LABEL}.plist`)

function writeAgentFiles(profileDir: string, port: number) {
  // Chrome's --user-data-dir must be the Chrome ROOT (parent of profile folders),
  // and --profile-directory selects which subfolder ("Default", "Profile 4", etc).
  // Passing the full profile path as --user-data-dir makes Chrome create a blank
  // new root with a fresh "Default" subprofile inside it.
  const userDataDir = path.dirname(profileDir)
  const profileFolder = path.basename(profileDir)

  const script = `#!/bin/bash
# Xiaoheishu — start Chrome with CDP debug port (managed by LaunchAgent)
# Auto-generated by Xiaoheishu desktop app

USER_DATA_DIR="${userDataDir}"
PROFILE_FOLDER="${profileFolder}"
PORT=${port}
LOG=/tmp/xiaoheishu-chrome.log

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG"; }

# Fast path: port already bound
if curl -s "http://localhost:$PORT/json/version" > /dev/null 2>&1; then
  log "Port $PORT already bound, nothing to do"
  exit 0
fi

log "Starting Chrome with CDP on port $PORT (profile: $PROFILE_FOLDER)"

# Kill any existing Chrome (graceful then forceful — osascript alone often
# leaves helper processes that block --remote-debugging-port from binding)
osascript -e 'tell application "Google Chrome" to quit' 2>/dev/null
sleep 2
pkill -f "Google Chrome" 2>/dev/null
sleep 1

# Remove singleton lock files — even after Chrome exits these can persist and
# prevent the CDP socket from being created on the next launch.
rm -f "$USER_DATA_DIR/SingletonLock" \\
      "$USER_DATA_DIR/SingletonSocket" \\
      "$USER_DATA_DIR/SingletonCookie" 2>/dev/null

# Launch Chrome with the user's actual profile + debug port
open -na "Google Chrome" --args \\
  --user-data-dir="$USER_DATA_DIR" \\
  --profile-directory="$PROFILE_FOLDER" \\
  --remote-debugging-port=$PORT \\
  --no-first-run \\
  --no-default-browser-check \\
  "https://creator.xiaohongshu.com/publish/publish?source=official"

# Poll for port to bind (up to 15 seconds) so we know launch actually succeeded
for i in $(seq 1 15); do
  if curl -s "http://localhost:$PORT/json/version" > /dev/null 2>&1; then
    log "Chrome CDP ready on port $PORT after ${i}s"
    exit 0
  fi
  sleep 1
done

log "WARNING: Chrome launched but port $PORT did not bind within 15s"
exit 1
`

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${AGENT_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${AGENT_SCRIPT}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>/tmp/xiaoheishu-chrome.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/xiaoheishu-chrome.err</string>
</dict>
</plist>
`

  fs.mkdirSync(path.dirname(AGENT_SCRIPT), { recursive: true })
  fs.writeFileSync(AGENT_SCRIPT, script, { mode: 0o755 })
  fs.mkdirSync(path.dirname(AGENT_PLIST), { recursive: true })
  fs.writeFileSync(AGENT_PLIST, plist)
}

function isAgentInstalled(): boolean {
  return fs.existsSync(AGENT_PLIST)
}

function isAgentRunning(): boolean {
  const r = spawnSync('launchctl', ['list', AGENT_LABEL], { encoding: 'utf-8' })
  return r.status === 0 && !r.stdout.includes('"PID" = ')  // has PID entry
    || (r.status === 0 && r.stdout.includes('PID'))
}

ipcMain.handle('xiaohongshu:login', async () => {
  await loginWithQR()
  return { ok: true }
})

ipcMain.handle('xiaohongshu:login-status', () => {
  return { loggedIn: hasCookies() }
})

ipcMain.handle('xiaohongshu:cdp-status', async (_e, port: number) => {
  const connected = await probeCdp(port)
  // Also check if Chrome process has the debug flag (diagnostic)
  const psResult = spawnSync('sh', ['-c', 'ps aux | grep "remote-debugging" | grep -v grep'], { encoding: 'utf-8' })
  const hasDebugFlag = psResult.stdout.trim().length > 0
  return { connected, hasDebugFlag, debugProcessLine: psResult.stdout.trim().slice(0, 120) }
})

ipcMain.handle('xiaohongshu:agent-status', () => {
  return { installed: isAgentInstalled(), running: isAgentRunning() }
})

ipcMain.handle('xiaohongshu:install-agent', (_e, profileDir: string, port: number) => {
  const resolved = profileDir.replace(/^~/, os.homedir())
  writeAgentFiles(resolved, port)
  // Unload first in case old version was loaded
  spawnSync('launchctl', ['unload', AGENT_PLIST], { encoding: 'utf-8' })
  const r = spawnSync('launchctl', ['load', AGENT_PLIST], { encoding: 'utf-8' })
  if (r.status !== 0) throw new Error(`launchctl load failed: ${r.stderr}`)
  return { ok: true }
})

ipcMain.handle('xiaohongshu:start-agent', () => {
  const r = spawnSync('launchctl', ['start', AGENT_LABEL], { encoding: 'utf-8' })
  if (r.status !== 0) throw new Error(`launchctl start failed: ${r.stderr}`)
  return { ok: true }
})

ipcMain.handle('xiaohongshu:uninstall-agent', () => {
  spawnSync('launchctl', ['unload', AGENT_PLIST], { encoding: 'utf-8' })
  try { fs.unlinkSync(AGENT_PLIST) } catch { /* ignore */ }
  return { ok: true }
})

ipcMain.handle('xiaohongshu:list-profiles', () => {
  const dataDir = path.join(require('os').homedir(), 'Library', 'Application Support', 'Google', 'Chrome')
  const localStatePath = path.join(dataDir, 'Local State')
  try {
    const raw = fs.readFileSync(localStatePath, 'utf-8')
    const state = JSON.parse(raw) as {
      profile?: { info_cache?: Record<string, { name?: string; user_name?: string; gaia_name?: string }> }
    }
    const cache = state.profile?.info_cache ?? {}
    return Object.entries(cache).map(([folder, info]) => ({
      folder,
      fullPath: path.join(dataDir, folder),
      name: info.name || folder,
      email: info.user_name || info.gaia_name || '',
    }))
  } catch {
    return []
  }
})

ipcMain.handle('settings:test-xhs', async (_e, username: string, password: string) => {
  if (!username || !password) throw new Error('Username and password not set')
  const res = await fetch(`https://${username}.xiaoheishu.xyz/api/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ password }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: res.statusText })) as { error?: string }
    throw new Error(err.error || `HTTP ${res.status}`)
  }
  return res.json()
})

ipcMain.handle('images:save', (_e, bytes: number[], ext: string) => {
  const dir = path.join(app.getPath('userData'), 'images')
  fs.mkdirSync(dir, { recursive: true })
  const filename = `img_${Date.now()}.${ext}`
  const filepath = path.join(dir, filename)
  fs.writeFileSync(filepath, Buffer.from(bytes))
  return filepath
})
